{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# b2bpvcshop — Ready worker.js\n",
        "\n",
        "এই code-টি GitHub-এর `worker.js`-এর সম্পূর্ণ code হিসেবে ব্যবহার করার জন্য প্রস্তুত।"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "const encoder = new TextEncoder();\n",
        "const SESSION_DAYS = 30;\n",
        "const LOGIN_LIMIT = 8;\n",
        "const ADMIN_USERNAME = 'owner';\n",
        "const loginAttempts = new Map();\n",
        "\n",
        "function json(data, status = 200, headers = {}) {\n",
        "  return new Response(JSON.stringify(data), {\n",
        "    status,\n",
        "    headers: {\n",
        "      'content-type': 'application/json; charset=utf-8',\n",
        "      ...headers\n",
        "    }\n",
        "  });\n",
        "}\n",
        "\n",
        "function b64(buf) {\n",
        "  let s = '';\n",
        "  const bytes = new Uint8Array(buf);\n",
        "  for (const b of bytes) s += String.fromCharCode(b);\n",
        "  return btoa(s);\n",
        "}\n",
        "\n",
        "function unb64(s) {\n",
        "  const bin = atob(s);\n",
        "  const a = new Uint8Array(bin.length);\n",
        "  for (let i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);\n",
        "  return a;\n",
        "}\n",
        "\n",
        "function randomToken() {\n",
        "  const a = new Uint8Array(32);\n",
        "  crypto.getRandomValues(a);\n",
        "  return b64(a).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '');\n",
        "}\n",
        "\n",
        "async function sha256(s) {\n",
        "  return crypto.subtle.digest('SHA-256', encoder.encode(s));\n",
        "}\n",
        "\n",
        "async function passwordHash(password, saltB64) {\n",
        "  const salt = saltB64 ? unb64(saltB64) : crypto.getRandomValues(new Uint8Array(16));\n",
        "\n",
        "  const key = await crypto.subtle.importKey(\n",
        "    'raw',\n",
        "    encoder.encode(password),\n",
        "    'PBKDF2',\n",
        "    false,\n",
        "    ['deriveBits']\n",
        "  );\n",
        "\n",
        "  const bits = await crypto.subtle.deriveBits(\n",
        "    {\n",
        "      name: 'PBKDF2',\n",
        "      salt,\n",
        "      iterations: 120000,\n",
        "      hash: 'SHA-256'\n",
        "    },\n",
        "    key,\n",
        "    256\n",
        "  );\n",
        "\n",
        "  return { salt: b64(salt), hash: b64(bits) };\n",
        "}\n",
        "\n",
        "async function verifyPassword(password, salt, expected) {\n",
        "  const x = await passwordHash(password, salt);\n",
        "  return x.hash === expected;\n",
        "}\n",
        "\n",
        "function cookie(name, value, maxAge) {\n",
        "  return `${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;\n",
        "}\n",
        "\n",
        "function clearCookie(name) {\n",
        "  return `${name}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`;\n",
        "}\n",
        "\n",
        "function getCookie(req, name) {\n",
        "  const c = req.headers.get('Cookie') || '';\n",
        "  const m = c.match(\n",
        "    new RegExp('(?:^|; )' + name.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&') + '=([^;]+)')\n",
        "  );\n",
        "  return m ? decodeURIComponent(m[1]) : null;\n",
        "}\n",
        "\n",
        "function cleanPhone(v) {\n",
        "  return String(v || '').replace(/\\D/g, '').slice(-10);\n",
        "}\n",
        "\n",
        "function validPassword(p) {\n",
        "  return typeof p === 'string' && p.length >= 8 && p.length <= 128;\n",
        "}\n",
        "\n",
        "function now() {\n",
        "  return new Date().toISOString();\n",
        "}\n",
        "\n",
        "async function body(req) {\n",
        "  try {\n",
        "    return await req.json();\n",
        "  } catch {\n",
        "    return {};\n",
        "  }\n",
        "}\n",
        "\n",
        "async function userFromSession(req, env) {\n",
        "  const token = getCookie(req, 'pvc_session');\n",
        "  if (!token) return null;\n",
        "\n",
        "  const digest = await sha256(token);\n",
        "  const hash = b64(digest);\n",
        "\n",
        "  const row = await env.DB.prepare(`\n",
        "    SELECT u.id, u.name, u.phone, u.address, u.pin, u.created_at\n",
        "    FROM sessions s\n",
        "    JOIN customers u ON u.id = s.user_id\n",
        "    WHERE s.token_hash = ? AND s.expires_at > ?\n",
        "  `).bind(hash, now()).first();\n",
        "\n",
        "  return row || null;\n",
        "}\n",
        "\n",
        "function publicUser(u) {\n",
        "  return u ? {\n",
        "    id: u.id,\n",
        "    name: u.name,\n",
        "    phone: u.phone,\n",
        "    address: u.address || '',\n",
        "    pin: u.pin || '',\n",
        "    createdAt: u.created_at\n",
        "  } : null;\n",
        "}\n",
        "\n",
        "async function requireUser(req, env) {\n",
        "  const u = await userFromSession(req, env);\n",
        "  if (!u) throw new Error('UNAUTHORIZED');\n",
        "  return u;\n",
        "}\n",
        "\n",
        "function rateLimit(req) {\n",
        "  const ip = req.headers.get('CF-Connecting-IP') || 'unknown';\n",
        "  const t = Date.now();\n",
        "  let a = loginAttempts.get(ip) || [];\n",
        "\n",
        "  a = a.filter(x => t - x < 15 * 60 * 1000);\n",
        "\n",
        "  if (a.length >= LOGIN_LIMIT) return true;\n",
        "\n",
        "  a.push(t);\n",
        "  loginAttempts.set(ip, a);\n",
        "  return false;\n",
        "}\n",
        "\n",
        "/* =========================\n",
        "   ADMIN AUTH\n",
        "========================= */\n",
        "\n",
        "async function requireAdmin(req, env) {\n",
        "  const c = req.headers.get('Cookie') || '';\n",
        "  const m = c.match(/(?:^|; )admin_session=([^;]+)/);\n",
        "\n",
        "  if (!m) throw new Error('UNAUTHORIZED');\n",
        "\n",
        "  const tokenHash = await sha256(m[1]);\n",
        "\n",
        "  const row = await env.DB.prepare(`\n",
        "    SELECT a.*\n",
        "    FROM admins a\n",
        "    JOIN admin_sessions s ON s.admin_id = a.id\n",
        "    WHERE s.token_hash = ? AND s.expires_at > ?\n",
        "  `).bind(b64(tokenHash), now()).first();\n",
        "\n",
        "  if (!row) throw new Error('UNAUTHORIZED');\n",
        "\n",
        "  return row;\n",
        "}\n",
        "\n",
        "function adminCookie(token) {\n",
        "  return `admin_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`;\n",
        "}\n",
        "\n",
        "async function ensureAdmin(env) {\n",
        "  const existing = await env.DB.prepare(\n",
        "    'SELECT id FROM admins WHERE username=?'\n",
        "  ).bind(ADMIN_USERNAME).first();\n",
        "\n",
        "  if (existing) return existing;\n",
        "\n",
        "  const initial = env.ADMIN_INITIAL_PASSWORD;\n",
        "\n",
        "  if (!initial || !validPassword(initial)) {\n",
        "    throw new Error('ADMIN_INITIAL_PASSWORD secret is not configured.');\n",
        "  }\n",
        "\n",
        "  const ph = await passwordHash(initial);\n",
        "\n",
        "  const r = await env.DB.prepare(`\n",
        "    INSERT INTO admins\n",
        "    (username,password_hash,password_salt,created_at,updated_at)\n",
        "    VALUES (?,?,?,?,?)\n",
        "  `).bind(\n",
        "    ADMIN_USERNAME,\n",
        "    ph.hash,\n",
        "    ph.salt,\n",
        "    now(),\n",
        "    now()\n",
        "  ).run();\n",
        "\n",
        "  return {\n",
        "    id: r.meta.last_row_id,\n",
        "    username: ADMIN_USERNAME\n",
        "  };\n",
        "}\n",
        "\n",
        "/* =========================\n",
        "   API\n",
        "========================= */\n",
        "\n",
        "async function api(req, env) {\n",
        "  const url = new URL(req.url);\n",
        "  const path = url.pathname;\n",
        "\n",
        "  if (req.method === 'POST' && path === '/api/auth/register') {\n",
        "    if (rateLimit(req)) {\n",
        "      return json({ error: 'Too many attempts. Please try again later.' }, 429);\n",
        "    }\n",
        "\n",
        "    const b = await body(req);\n",
        "    const name = String(b.name || '').trim();\n",
        "    const phone = cleanPhone(b.phone);\n",
        "    const password = String(b.password || '');\n",
        "\n",
        "    if (name.length < 2 || phone.length !== 10 || !validPassword(password)) {\n",
        "      return json({\n",
        "        error: 'Name, valid 10-digit mobile and password (8+ characters) are required.'\n",
        "      }, 400);\n",
        "    }\n",
        "\n",
        "    const exists = await env.DB.prepare(\n",
        "      'SELECT id FROM customers WHERE phone=?'\n",
        "    ).bind(phone).first();\n",
        "\n",
        "    if (exists) {\n",
        "      return json({ error: 'Account already exists. Please login.' }, 409);\n",
        "    }\n",
        "\n",
        "    const ph = await passwordHash(password);\n",
        "\n",
        "    const r = await env.DB.prepare(`\n",
        "      INSERT INTO customers\n",
        "      (name,phone,password_hash,password_salt,address,pin,created_at)\n",
        "      VALUES (?,?,?,?,?,?,?)\n",
        "    `).bind(\n",
        "      name,\n",
        "      phone,\n",
        "      ph.hash,\n",
        "      ph.salt,\n",
        "      String(b.address || '').trim(),\n",
        "      String(b.pin || '').trim(),\n",
        "      now()\n",
        "    ).run();\n",
        "\n",
        "    const id = r.meta.last_row_id;\n",
        "    const token = randomToken();\n",
        "    const th = b64(await sha256(token));\n",
        "    const exp = new Date(Date.now() + SESSION_DAYS * 86400000).toISOString();\n",
        "\n",
        "    await env.DB.prepare(`\n",
        "      INSERT INTO sessions\n",
        "      (token_hash,user_id,expires_at,created_at)\n",
        "      VALUES (?,?,?,?)\n",
        "    `).bind(th, id, exp, now()).run();\n",
        "\n",
        "    const u = await env.DB.prepare(`\n",
        "      SELECT id,name,phone,address,pin,created_at\n",
        "      FROM customers WHERE id=?\n",
        "    `).bind(id).first();\n",
        "\n",
        "    return json(\n",
        "      { user: publicUser(u) },\n",
        "      200,\n",
        "      { 'Set-Cookie': cookie('pvc_session', token, SESSION_DAYS * 86400) }\n",
        "    );\n",
        "  }\n",
        "\n",
        "  if (req.method === 'POST' && path === '/api/auth/login') {\n",
        "    if (rateLimit(req)) {\n",
        "      return json({ error: 'Too many login attempts. Please try again later.' }, 429);\n",
        "    }\n",
        "\n",
        "    const b = await body(req);\n",
        "    const phone = cleanPhone(b.phone);\n",
        "    const password = String(b.password || '');\n",
        "\n",
        "    if (phone.length !== 10 || !password) {\n",
        "      return json({ error: 'Invalid login details.' }, 401);\n",
        "    }\n",
        "\n",
        "    const u = await env.DB.prepare(\n",
        "      'SELECT * FROM customers WHERE phone=?'\n",
        "    ).bind(phone).first();\n",
        "\n",
        "    if (!u || !(await verifyPassword(password, u.password_salt, u.password_hash))) {\n",
        "      return json({ error: 'Invalid mobile number or password.' }, 401);\n",
        "    }\n",
        "\n",
        "    const token = randomToken();\n",
        "    const th = b64(await sha256(token));\n",
        "    const exp = new Date(Date.now() + SESSION_DAYS * 86400000).toISOString();\n",
        "\n",
        "    await env.DB.prepare(`\n",
        "      INSERT INTO sessions\n",
        "      (token_hash,user_id,expires_at,created_at)\n",
        "      VALUES (?,?,?,?)\n",
        "    `).bind(th, u.id, exp, now()).run();\n",
        "\n",
        "    return json(\n",
        "      { user: publicUser(u) },\n",
        "      200,\n",
        "      { 'Set-Cookie': cookie('pvc_session', token, SESSION_DAYS * 86400) }\n",
        "    );\n",
        "  }\n",
        "\n",
        "  if (req.method === 'POST' && path === '/api/auth/logout') {\n",
        "    const token = getCookie(req, 'pvc_session');\n",
        "\n",
        "    if (token) {\n",
        "      await env.DB.prepare(\n",
        "        'DELETE FROM sessions WHERE token_hash=?'\n",
        "      ).bind(b64(await sha256(token))).run();\n",
        "    }\n",
        "\n",
        "    return json(\n",
        "      { ok: true },\n",
        "      200,\n",
        "      { 'Set-Cookie': clearCookie('pvc_session') }\n",
        "    );\n",
        "  }\n",
        "\n",
        "  if (req.method === 'GET' && path === '/api/auth/me') {\n",
        "    const u = await userFromSession(req, env);\n",
        "    return json({ user: publicUser(u) });\n",
        "  }\n",
        "\n",
        "  /* =========================\n",
        "     ADMIN LOGIN\n",
        "  ========================= */\n",
        "\n",
        "  if (req.method === 'POST' && path === '/api/admin/login') {\n",
        "    if (rateLimit(req)) {\n",
        "      return json({ error: 'Too many login attempts. Please try again later.' }, 429);\n",
        "    }\n",
        "\n",
        "    const b = await body(req);\n",
        "    const username = String(b.username || '').trim();\n",
        "    const password = String(b.password || '');\n",
        "\n",
        "    if (username !== ADMIN_USERNAME || !validPassword(password)) {\n",
        "      return json({ error: 'Invalid username or password.' }, 401);\n",
        "    }\n",
        "\n",
        "    try {\n",
        "      const admin = await ensureAdmin(env);\n",
        "\n",
        "      const row = await env.DB.prepare(\n",
        "        'SELECT * FROM admins WHERE id=?'\n",
        "      ).bind(admin.id).first();\n",
        "\n",
        "      if (!row || !(await verifyPassword(\n",
        "        password,\n",
        "        row.password_salt,\n",
        "        row.password_hash\n",
        "      ))) {\n",
        "        return json({ error: 'Invalid username or password.' }, 401);\n",
        "      }\n",
        "\n",
        "      const token = randomToken();\n",
        "      const th = b64(await sha256(token));\n",
        "      const exp = new Date(Date.now() + 43200000).toISOString();\n",
        "\n",
        "      await env.DB.prepare(`\n",
        "        INSERT INTO admin_sessions\n",
        "        (admin_id,token_hash,expires_at,created_at)\n",
        "        VALUES (?,?,?,?)\n",
        "      `).bind(admin.id, th, exp, now()).run();\n",
        "\n",
        "      return json(\n",
        "        { ok: true },\n",
        "        200,\n",
        "        { 'Set-Cookie': adminCookie(token) }\n",
        "      );\n",
        "    } catch (e) {\n",
        "      return json({ error: e.message || 'Admin login failed.' }, 500);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (req.method === 'POST' && path === '/api/admin/logout') {\n",
        "    const token = getCookie(req, 'admin_session');\n",
        "\n",
        "    if (token) {\n",
        "      await env.DB.prepare(\n",
        "        'DELETE FROM admin_sessions WHERE token_hash=?'\n",
        "      ).bind(b64(await sha256(token))).run();\n",
        "    }\n",
        "\n",
        "    return json(\n",
        "      { ok: true },\n",
        "      200,\n",
        "      {\n",
        "        'Set-Cookie':\n",
        "          'admin_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict'\n",
        "      }\n",
        "    );\n",
        "  }\n",
        "\n",
        "  if (req.method === 'GET' && path === '/api/admin/me') {\n",
        "    try {\n",
        "      const a = await requireAdmin(req, env);\n",
        "\n",
        "      return json({\n",
        "        admin: {\n",
        "          id: a.id,\n",
        "          username: a.username\n",
        "        }\n",
        "      });\n",
        "    } catch {\n",
        "      return json({ admin: null }, 401);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (\n",
        "    path === '/api/account/profile' &&\n",
        "    (req.method === 'PUT' || req.method === 'PATCH')\n",
        "  ) {\n",
        "    try {\n",
        "      const u = await requireUser(req, env);\n",
        "      const b = await body(req);\n",
        "\n",
        "      const name = String(b.name ?? u.name).trim();\n",
        "      const address = String((b.address ?? u.address) || '').trim();\n",
        "      const pin = String((b.pin ?? u.pin) || '').trim();\n",
        "\n",
        "      if (name.length < 2) {\n",
        "        return json({ error: 'Name is required.' }, 400);\n",
        "      }\n",
        "\n",
        "      await env.DB.prepare(`\n",
        "        UPDATE customers SET name=?,address=?,pin=? WHERE id=?\n",
        "      `).bind(name, address, pin, u.id).run();\n",
        "\n",
        "      const n = await env.DB.prepare(`\n",
        "        SELECT id,name,phone,address,pin,created_at\n",
        "        FROM customers WHERE id=?\n",
        "      `).bind(u.id).first();\n",
        "\n",
        "      return json({ user: publicUser(n) });\n",
        "    } catch (e) {\n",
        "      return json({\n",
        "        error: e.message === 'UNAUTHORIZED' ? 'Please login.' : 'Unable to update profile.'\n",
        "      }, 401);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (path === '/api/account/password' && req.method === 'PUT') {\n",
        "    try {\n",
        "      const u = await requireUser(req, env);\n",
        "      const b = await body(req);\n",
        "\n",
        "      const old = String(b.currentPassword || '');\n",
        "      const next = String(b.newPassword || '');\n",
        "\n",
        "      const row = await env.DB.prepare(\n",
        "        'SELECT * FROM customers WHERE id=?'\n",
        "      ).bind(u.id).first();\n",
        "\n",
        "      if (!await verifyPassword(old, row.password_salt, row.password_hash)) {\n",
        "        return json({ error: 'Current password is incorrect.' }, 400);\n",
        "      }\n",
        "\n",
        "      if (!validPassword(next)) {\n",
        "        return json({ error: 'New password must be at least 8 characters.' }, 400);\n",
        "      }\n",
        "\n",
        "      const ph = await passwordHash(next);\n",
        "\n",
        "      await env.DB.prepare(`\n",
        "        UPDATE customers\n",
        "        SET password_hash=?,password_salt=?\n",
        "        WHERE id=?\n",
        "      `).bind(ph.hash, ph.salt, u.id).run();\n",
        "\n",
        "      return json({ ok: true });\n",
        "    } catch {\n",
        "      return json({ error: 'Please login.' }, 401);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (path === '/api/cart' && req.method === 'GET') {\n",
        "    try {\n",
        "      const u = await requireUser(req, env);\n",
        "\n",
        "      const rows = await env.DB.prepare(`\n",
        "        SELECT product_id,quantity\n",
        "        FROM carts\n",
        "        WHERE user_id=?\n",
        "        ORDER BY updated_at DESC\n",
        "      `).bind(u.id).all();\n",
        "\n",
        "      return json({ items: rows.results || [] });\n",
        "    } catch {\n",
        "      return json({ error: 'Please login.' }, 401);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (path === '/api/cart' && req.method === 'PUT') {\n",
        "    try {\n",
        "      const u = await requireUser(req, env);\n",
        "      const b = await body(req);\n",
        "      const items = Array.isArray(b.items) ? b.items : [];\n",
        "\n",
        "      await env.DB.prepare(\n",
        "        'DELETE FROM carts WHERE user_id=?'\n",
        "      ).bind(u.id).run();\n",
        "\n",
        "      for (const x of items) {\n",
        "        const pid = String(x.product_id || x.id || '');\n",
        "        const qty = Math.max(\n",
        "          1,\n",
        "          Math.min(999, Number(x.quantity || x.qty) || 1)\n",
        "        );\n",
        "\n",
        "        if (pid) {\n",
        "          await env.DB.prepare(`\n",
        "            INSERT INTO carts\n",
        "            (user_id,product_id,quantity,updated_at)\n",
        "            VALUES (?,?,?,?)\n",
        "          `).bind(u.id, pid, qty, now()).run();\n",
        "        }\n",
        "      }\n",
        "\n",
        "      return json({ ok: true });\n",
        "    } catch {\n",
        "      return json({ error: 'Please login.' }, 401);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (path === '/api/orders' && req.method === 'GET') {\n",
        "    try {\n",
        "      const u = await requireUser(req, env);\n",
        "\n",
        "      const orders = await env.DB.prepare(`\n",
        "        SELECT *\n",
        "        FROM orders\n",
        "        WHERE customer_id=?\n",
        "        ORDER BY created_at DESC\n",
        "        LIMIT 100\n",
        "      `).bind(u.id).all();\n",
        "\n",
        "      return json({ orders: orders.results || [] });\n",
        "    } catch {\n",
        "      return json({ error: 'Please login.' }, 401);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (path === '/api/orders' && req.method === 'POST') {\n",
        "    try {\n",
        "      const u = await requireUser(req, env);\n",
        "      const b = await body(req);\n",
        "      const items = Array.isArray(b.items) ? b.items : [];\n",
        "\n",
        "      if (!items.length) {\n",
        "        return json({ error: 'Cart is empty.' }, 400);\n",
        "      }\n",
        "\n",
        "      const orderNo =\n",
        "        'WB-PVC-' +\n",
        "        Math.floor(100000 + Math.random() * 900000);\n",
        "\n",
        "      await env.DB.prepare(`\n",
        "        INSERT INTO orders\n",
        "        (order_no,customer_id,items_json,subtotal,delivery,total,status,created_at)\n",
        "        VALUES (?,?,?,?,?,?,?,?)\n",
        "      `).bind(\n",
        "        orderNo,\n",
        "        u.id,\n",
        "        JSON.stringify(items),\n",
        "        Number(b.subtotal) || 0,\n",
        "        Number(b.delivery) || 0,\n",
        "        Number(b.total) || 0,\n",
        "        'Order Received',\n",
        "        now()\n",
        "      ).run();\n",
        "\n",
        "      await env.DB.prepare(\n",
        "        'DELETE FROM carts WHERE user_id=?'\n",
        "      ).bind(u.id).run();\n",
        "\n",
        "      return json({ orderNo });\n",
        "    } catch {\n",
        "      return json({ error: 'Could not create order.' }, 500);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  if (path === '/api/feedback' && req.method === 'POST') {\n",
        "    try {\n",
        "      const u = await requireUser(req, env);\n",
        "      const b = await body(req);\n",
        "\n",
        "      await env.DB.prepare(`\n",
        "        INSERT INTO feedback\n",
        "        (customer_id,type,message,created_at)\n",
        "        VALUES (?,?,?,?)\n",
        "      `).bind(\n",
        "        u.id,\n",
        "        String(b.type || 'feedback'),\n",
        "        String(b.message || '').slice(0, 2000),\n",
        "        now()\n",
        "      ).run();\n",
        "\n",
        "      return json({ ok: true });\n",
        "    } catch {\n",
        "      return json({ error: 'Please login.' }, 401);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  return null;\n",
        "}\n",
        "\n",
        "export default {\n",
        "  async fetch(req, env) {\n",
        "    try {\n",
        "      if (new URL(req.url).pathname.startsWith('/api/')) {\n",
        "        const r = await api(req, env);\n",
        "        if (r) return r;\n",
        "\n",
        "        return json({ error: 'Not found' }, 404);\n",
        "      }\n",
        "\n",
        "      return env.ASSETS.fetch(req);\n",
        "    } catch (e) {\n",
        "      console.error(e);\n",
        "      return json({ error: 'Server error' }, 500);\n",
        "    }\n",
        "  }\n",
        "};\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "JavaScript",
      "language": "javascript",
      "name": "javascript"
    },
    "language_info": {
      "name": "javascript"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
